version: '2'
services:
  peopleprofilemicroservices-app:
    image: peopleprofilemicroservices
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://peopleprofilemicroservices-mysql:3306/peopleprofilemicroservices?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  peopleprofilemicroservices-mysql:
    extends:
      file: mysql.yml
      service: peopleprofilemicroservices-mysql
